### ISSUE TITLE
python3.5 运行报错

### ISSUE THREAD

**Issue by yavana** [wangliangliang2/pili-python3.5#1]
Traceback (most recent call last):
  File "F:/1/wz/qiniu/pili-python3.5-master/example.py", line 50, in <module>
    print ("\nget_stream()\n", stream.to_json())
  File "F:\1\wz\qiniu\pili-python3.5-master\pili\stream.py", line 116, in to_json
    return json.dumps(self.data)
  File "F:\1\wz\qiniu\pili-python3.5-master\pili\stream.py", line 23, in __getattr__
    self.refresh()
  File "F:\1\wz\qiniu\pili-python3.5-master\pili\stream.py", line 30, in refresh
    self.__data__ = api.get_stream(self.__auth__, stream_id=self.id)
  File "F:\1\wz\qiniu\pili-python3.5-master\pili\auth.py", line 59, in authed
    return send_and_decode(req)
  File "F:\1\wz\qiniu\pili-python3.5-master\pili\utils.py", line 34, in send_and_decode
    raise APIError(data["error"])
pili.errors.APIError: no routes found

**Comment by wangliangliang2** [comment]
fixed
